# $Id$

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = multilingual.xml
TARGET = index.php intro.php files.php procedure.php resources.php appendix.php
=======
WANT_HTML = 1
DESTDIR = doc/multilingual

LANGUAGES = en
include $(basedir)/Makefile.i18n.common
=======

# eof

