#! /bin/sh

# Useful script for generating tarballs and updating .info files for
# packages (like OpenMCL) that track CVS


PACKAGE="openmcl"
VERSION="0.14.2"
WD=`pwd`
STAGING=`mktemp -d`

rm -f $PACKAGE-cvs*.tar.bz2

cd $STAGING
  cvs -d :pserver:cvs@clozure.com:/usr/local/tmpcvs/ccl-0.14 get ccl
  cd ccl 
    cvs2cl
    DATE=`awk -F'[- ]' '$NR ~ 0 { printf "%02i%02i%02i",($1-2000),$2,$3 }' ChangeLog`
  cd $STAGING
  find $STAGING -type d -name "CVS" -depth -exec rm -rf {} \;
  find $STAGING -type f -name ".cvsignore" -exec rm -f {} \;
  TARNAME=$PACKAGE-cvs-$VERSION.$DATE.tar.bz2
  tar cvfj $WD/$TARNAME ccl
cd $WD

rm -rf $STAGING

# update the fink .info file
MD5=`md5sum $TARNAME | awk '{print $1}'`

sed $PACKAGE.info.in \
    -e "s|@DATE@|$DATE|g" \
    -e "s|@VERSION@|$VERSION|g" \
    -e "s|@TARNAME@|$TARNAME|g" \
    -e "s|@MD5@|$MD5|g" > $PACKAGE.info

echo "Update complete!"
