#!/bin/sh
factor = 3

case $1 in
	start	) operand=\*	;;
	stop	) operand=\/	;;
	*	)	exit 1	;;
esac

for val in kern.sysv.shmmax kern.sysv.shmmin kern.sysv.shmmni kern.sysv.shmseg kern.sysv.shmall
do

	oldval = `sysctl $val | awk '{print $2}'`
	newval = `echo $oldval $operand $factor | bc`

	sysctl $val=$newval
done
