# $Id$

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = quick-start-pkg.xml
TARGET = index.php howtostart.php example1.php example2.php
WANT_HTML = 1
DESTDIR = doc/quick-start-pkg

LANGUAGES = en
include $(basedir)/Makefile.i18n.common

# eof
