#!/bin/sh

locate bom | grep -E '\.bom$' | while read LINE; do
	if lsbom -s "$LINE" 2>&1 | grep -q "$@"; then
		echo "$LINE" | sed -e 's,^/Library/Receipts/,,' -e 's,/.*$,,'
	fi
done | sort -u | grep -v -E '^$'
