# $Id$

# process XML files with stylesheet to produce HTML

basedir = ..

WANT_HTML = 1
DESTDIR = faq

SOURCE = faq.ja.xml
TARGET = index.ja.php general.ja.php relations.ja.php \
	 usage-fink.ja.php comp-general.ja.php comp-packages.ja.php \
	 usage-general.ja.php usage-packages.ja.php upgrade-fink.ja.php
	 
 include $(basedir)/Makefile.common

# eof
