# $Id$

# process XML files with stylesheet to produce HTML

basedir = ..

SOURCE = quick-start-pkg.xml
# The second example is not ready yet...
#TARGET = index.php howtostart.php example.php example2.php example3.php
TARGET = index.php howtostart.php example.php example3.php
WANT_HTML = 1
DESTDIR = doc/quick-start-pkg

LANGUAGES = en
include $(basedir)/Makefile.i18n.common

# eof
