#!/bin/sh
# greps through all receipts in /Library/Receipts
[ -z $1 ] && exec echo "usage: grepbom REGEXP" 

IFS="
"
for BOM in `find /Library/Receipts/ -name \*.bom`  
do  
  CR=1 
  printf "."  
  lsbom -p MUGsfT $BOM |grep $1 && printf "   ====> %s\n\n" $BOM && CR=0 
done
[ ${CR} -gt 0 ] &&  printf "\n" 

