#!/usr/bin/perl

$|++;

use CPAN;
use vars qw(
	$VERSION
	$MODULE
	$SEARCH_PACKAGE
	$PACKAGE_NAME
	$PACKAGE_VERSION
	$PACKAGE_MD5
	$FILENAME
	$FULL_FILENAME
	$FETCH_CMD
);

unless (@ARGV) {
	print <<END;
usage: $0 <perl_module> [package_name]

END
	exit 1;
}

$VERSION        = '0.1';
$SEARCH_PACKAGE = shift @ARGV;
$PACKAGE_NAME   = shift @ARGV;

my @modules = CPAN::Shell->expand('Module', '/' . $SEARCH_PACKAGE . '/');

if (@modules > 1) {
	for my $module (@modules) {
		if (lc($module->id) eq lc($SEARCH_PACKAGE)) {
			$MODULE = $module;
		}
	}

	unless (defined $MODULE) {
		print "\n* fink2cpan found more than one module that matches:\n\n";
		for my $index (0..$#modules) {
			printf("  \%3d  \%s\n", $index, $modules[$index]->id);
		}
		print "\n  choose one: ";
		chomp(my $input = <STDIN>);
		if ($input =~ /^\d+$/ and defined $modules[$input]) {
			$MODULE = $modules[$input];
		}
	}
} else {
	$MODULE = $modules[0];
}

unless (defined $PACKAGE_NAME) {
	$PACKAGE_NAME = lc($MODULE->cpan_file);
	$PACKAGE_NAME =~ s/^.*\///;
	$PACKAGE_NAME =~ s/-[^\-]+\.tar\.\w+$//;
	$PACKAGE_NAME =~ s/[^a-z\-]+/-/gs;
	$PACKAGE_NAME =~ s/^bundle-//;
}

$PACKAGE_NAME .= '-pm' unless ($PACKAGE_NAME =~ /-pm$/);

if ($PACKAGE_NAME eq "perl-pm") {
	die "Whoa!  You've got some bad dependency mojo.  Stop trying to package perl!\n";
}

$FULL_FILENAME = $MODULE->cpan_file;
$FILENAME = $FULL_FILENAME;
$FILENAME =~ s/^.*\///;

$PACKAGE_VERSION =  lc($FILENAME);
$PACKAGE_VERSION =~ s/^[^\/]+-//;
$PACKAGE_VERSION =~ s/\.tar\.\w+$//;

print "\n*** creating package '$PACKAGE_NAME' with '$FILENAME', version ", $PACKAGE_VERSION, " ***\n\n";

chomp($FETCH_CMD=`which curl 2>/dev/null`);
if ($FETCH_CMD =~ /^\s*$/) {
	die "unable to find curl!";
}

chomp(my $fink_prefix = `which fink 2>/dev/null`);
$fink_prefix =~ s/\/bin\/fink.*//;

system("${FETCH_CMD} -o ${fink_prefix}/src/${FILENAME} ftp://mirrors.rcn.net/pub/lang/CPAN/authors/id/${FULL_FILENAME}");
chomp($PACKAGE_MD5=`md5sum ${fink_prefix}/src/${FILENAME} 2>/dev/null`);
($PACKAGE_MD5)=split(/\s+/, $PACKAGE_MD5);

system("mkdir -p ${fink_prefix}/fink/dists/local/main/finkinfo/libs/perlmods");
open (FILEOUT, ">${fink_prefix}/fink/dists/local/main/finkinfo/libs/perlmods/${PACKAGE_NAME}-${PACKAGE_VERSION}-1.info") or
	die "can't write to ${PACKAGE_NAME}-${PACKAGE_VERSION}-1.info: $!\n";
print FILEOUT <<END;
Package: $PACKAGE_NAME
Version: $PACKAGE_VERSION
Revision: 1
Description: CPAN2Fink Perl Module: $PACKAGE_NAME
Type: perl
License: Artistic
Maintainer: None <fink-devel\@lists.sourceforge.net>

Source: mirror:cpan:authors/id/${FULL_FILENAME}
Source-MD5: $PACKAGE_MD5

UpdatePOD: true

DescDetail: <<
  This package was generated with cpan2fink.pl version $VERSION
<<

Homepage: http://www.cpan.org/
END
close (FILEOUT);

system("fink install ${PACKAGE_NAME}");

print <<END;






*** ALL DONE ***

END

print <<END;
Please check your scrollback for errors, otherwise you're set.

An info file has been created:

${fink_prefix}/fink/dists/local/main/finkinfo/libs/perlmods/${PACKAGE_NAME}-${PACKAGE_VERSION}-1.info

It will work, but is very rudimentary.  Please update it by
adding a proper description, maintainer, and other package
information.

END
